# Generated by Django 5.1.3 on 2024-12-13 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phoneotp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 14 digits allowed.', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
