# """
# Django settings for videochat project.

# Generated by 'django-admin startproject' using Django 5.1.3.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=bp@q&ak%%@i6(vbea6enlw7%%iqt4gey^oe@*r21c+=yw=(w#'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     #'email_confirmation',
    

# # Other installed apps in the project
#     'chat',
#     'channels',
#     'base',
#     'accounts',
#     'rest_framework',
#     'knox',
#     'django.contrib.sites', 
#     'allauth',
#     'allauth.account',
#     'allauth.socialaccount',

#    # 'django_email_verification',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'allauth.account.middleware.AccountMiddleware',
# ]

# ROOT_URLCONF = 'videochat.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# #WSGI_APPLICATION = 'videochat.wsgi.application'
# ASGI_APPLICATION = 'videochat.asgi.application'



# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# #AUTH_KEY = 'url = f"https://control.msg91.com/api/sendotp.php?otp={otp}&message=Your otp is {otp}&mobile={mobile}&authkey={authkey}&country=254",

# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]

# #AUTH_USER_MODEL = 'accounts.User'

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTIFICATION_CLASSES' : (
#         'knox.auth.TokenAuthentication',
#         #'rest_framework.authetification.sessionAuthentification',
#           'rest_framework.authentication.TokenAuthentication',  
#     ),
# }

# from datetime import timedelta  

# REST_KNOX = {
#     'USER_SERIALIZER': 'accounts.UserSerializer',
#     'TOKEN_TTL' : timedelta(hours=24),
# }

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CHANNEL_LAYERS = {
#     'default':{
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#         # 'CONFIG' : {
#         #     'hosts': [('127.0.0.1',)],
#         # }
#     }
# }


# #EMAIL VERIFICATION

# # EMAIL_ACTIVE_FIELD = 'is_active'
# # EMAIL_SERVER = 'smtp.gmail.com'
# # EMAIL_PORT = 587
# # EMAIL_ADRESS = 'joshua12548@gmail.com'
# # EMAIL_FROM_ADRESS = 'joshua12548@gmail.com'
# # EMAIL_PASSWORD ='Om0ndi#34'
# # EMAIL_MAIL_SUBJECT = 'confirm your email'
# # EMAIL_MAIL_HTML = 'mail_body.html'
# # EMAIL_MAIL_PLAIN = 'mail_body.txt'
# # EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
# # EMAIL_PAGE_DOMAIN = 'http://127.0.0.1:8000/'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com' 
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'mentaleaase@gmail.com'  
# EMAIL_HOST_PASSWORD = 'Om0ndi#34' 
# DEFAULT_FROM_EMAIL = 'mentaleaase@gmail.com'

# # Authentication backends for Allauth and Django
# AUTHENTICATION_BACKENDS = (
#     'allauth.account.auth_backends.AuthenticationBackend',  # Allauth authentication backend
#     'django.contrib.auth.backends.ModelBackend',  # Default Django auth backend
# )

# # After login, redirect to homepage
# LOGIN_REDIRECT_URL = '/' 

# # Email confirmation and verification settings
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Email verification will be required
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1  # Email confirmation expiry time
# ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True  # Redirect after successful login

# # Site ID setting for Django Allauth
# SITE_ID = 1

from pathlib import Path
from datetime import timedelta

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = 'django-insecure-=bp@q&ak%%@i6(vbea6enlw7%%iqt4gey^oe@*r21c+=yw=(w#'
DEBUG = True
ALLOWED_HOSTS = []

# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'chat',
    'channels',
    'base',
    'accounts',
    'rest_framework',
    'knox',
    'django.contrib.sites', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# URL configuration
ROOT_URLCONF = 'videochat.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 
            BASE_DIR / 'accounts/templates',
                 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI/ASGI application
ASGI_APPLICATION = 'videochat.asgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# REST framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}

# Knox settings
REST_KNOX = {
    'USER_SERIALIZER': 'accounts.UserSerializer',
    'TOKEN_TTL': timedelta(hours=24),
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels layers
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# Email backend settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'joshua12548@gmail.com' #'mentaleaase@gmail.com'
EMAIL_HOST_PASSWORD = 'yaov itpx fbfe cxza' #'Om0ndi#34'
DEFAULT_FROM_EMAIL = 'mentaleaase@gmail.com'

# Authentication backends
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Allauth settings
LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

# Site ID
SITE_ID = 1
